server {
    listen              443 ssl;
    server_name         gtourdia.42.fr;
    ssl_certificate     /etc/nginx/certificate.pem;
    ssl_certificate_key /etc/nginx/certificate.key;
    ssl_protocols       TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
}