version: "3.8"

services:

  nginx:
    image: nginx
    depends_on: ['mariadb']
    ports:
    - 443:443
    networks:
      devnetwork:

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
    - 3306:3306
    networks:
      devnetwork:
    volumes:
      - db-data:/var/lib/mysql

networks:
  devnetwork:

volumes:
  db-data:
